
var BLOCK_WALL 		= 0;
var BLOCK_DOOR 		= 1;
var BLOCK_FWD 		= 2;
var BLOCK_BWD 		= 3;
var BLOCK_NOBOX 	= 4;
var BLOCK_BUTTON 	= 5;
var BLOCK_LASER 	= 6;
var BLOCK_BOX 		= 7;
var BLOCK_SPAWN 	= 8;
var BLOCK_EXIT 		= 9;
var BLOCK_ONEWAY 	= 10;
var BLOCK_TRIGGER 	= 11;
var BLOCK_LEVELSELECT 	= 12;
var BLOCK_HINT 		= 13;

var BLOCKSIZE		= 30;
var NUM_BLOCKS		= 16;
var SCR_SIZE		= 18;
var SPEED			= 0.05;
var RADIUS			= 0.299;
var TIMELINES_LEN	= 20;

var KEY_SPACE		= 32;
var KEY_GRAB		= 90;
var KEY_PAUSE		= 80;
var KEY_RESTART		= 82;
var KEY_QUIT		= 81;
var KEY_MUTE		= 77;

var REPLAY_STATE_NONE = 0;
var REPLAY_STATE_REWIND = 1;
var REPLAY_STATE_FWD = 2;

var REPLAY_REW_SPEED = 10;
var REPLAY_FWD_SPEED = 2;
var REPLAY_IMMOBILE_WAIT = 120;
var REPLAY_BUFFER = 60;

var abs = Math.abs;